# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "JOGOS" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,"titulo" VARCHAR NOT NULL,"capa" VARCHAR NOT NULL,"data" TIMESTAMP NOT NULL,"disponibilidade" BOOLEAN NOT NULL);

# --- !Downs

drop table "JOGOS";

